name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          poetry install --no-interaction --no-ansi
      - name: Run backend tests
        working-directory: ./backend
        run: |
          poetry run pytest
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install frontend dependencies and run tests
        working-directory: ./frontend
        run: |
          npm install && npm test -- --watchAll=false
